RGB emergency - Add support for RGB channel, and use button long press to toggle effect
pimoroni/picofx pull request #13
Opened 2024-11-13 15:15 UTC by tyeth

I've only got RGB LEDs 🎨 so this adds support for those, along with an orange hazard light mode if the boot button is held rather than pressed.

The onboard LED is also active so that's a nice touch (it's a lovely board).

Note to self:
Next I need to look at understanding the sequence functions better (checkout flashing(0)), or adding an easier way of having flashing RGB FX functions

Maybe this is over the top, let me know, but it also serves as a useful example.
Also please do feel free to find a better orange, I randomly picked using browser dev tools and was totally unhappy with the result so starting abusing the rgb values 🤓

2024-11-14 18:56 UTC, tyeth commented
Having played a bit more, it appears that replacing the effects property has not stopped the hazard effect correctly. Not got time to poke at it now, will revisit

2024-11-14 19:27 UTC, tyeth commented
https://youtu.be/xP5sYRU8vQA for a display of the behaviour. I swear when I first ran it there was a simple red/blue flash then after button held it went slow orange flash, and back to blue/red when button held again. Tested a few times. Since then two days have elapsed, one more random plugging in, and then moved upstairs to final spot for a bit of in-view testing.

2024-11-15 10:56 UTC, ZodiusInfuser commented
Hi @tyeth, Thank you for this example! It's quite a nice addition to the simple `rescue_vehicle.py` I wrote.

> Maybe this is over the top, let me know, but it also serves as a useful example.

It's not over the top but it would perhaps be better to submit it as a standalone example, rather than modify the existing one, so others may also benefit from having the same starting point as you in the future. `sea_rescue_vehicle.py` perhaps?

I'll submit some specific code comments after this.

> Also please do feel free to find a better orange, I randomly picked using browser dev tools and was totally unhappy with the result so starting abusing the rgb values 🤓

I only tested with the onboard LED, but (255, 32, 0) looked pretty orange to me. Having that last component be zero is key as that's the blue channel, which orange is famous for not having any of 😆 

> Next I need to look at understanding the sequence functions better (checkout flashing(0)), or adding an easier way of having flashing RGB FX functions

This could perhaps be solved by a dedicated RGBFlashingFX 🤔 

> https://youtu.be/xP5sYRU8vQA for a display of the behaviour. I swear when I first ran it there was a simple red/blue flash then after button held it went slow orange flash, and back to blue/red when button held again. Tested a few times.

Thanks for that video. I am really not sure what is going on there. I've not had it happen yet in my quick testing here. I admit I never tried switching loaded effects on the fly as you have done, so there could well be an edge case happening where the old effect is still being held on to. If you do raise an issue, having a minimal code example that produces the issue would be very helpful for debugging.

2024-11-15 11:09 UTC, ZodiusInfuser requested changes

2024-11-15 11:09 UTC, ZodiusInfuser commented on examples/tiny_fx/examples/showcase/rescue_vehicle.py
> +    dont_exit_yet = True
A simpler name would be `running` 😉

2024-11-15 11:09 UTC, ZodiusInfuser commented on examples/tiny_fx/examples/showcase/rescue_vehicle.py
> +        player.start()   # Start the effects running
I think `start()` should be outside of the first while loop. I wonder if repeated calls to it without calling stop first is the cause of your problem 🤔

2024-11-15 11:09 UTC, ZodiusInfuser commented on examples/tiny_fx/examples/showcase/rescue_vehicle.py
> +        while player.is_running() and not tiny.boot_pressed():
The player is never stopped, so checking `is_running()` is unnecessary

2024-11-15 11:09 UTC, ZodiusInfuser commented on examples/tiny_fx/examples/showcase/rescue_vehicle.py
> +        while player.is_running() and tiny.boot_pressed():
checking `is_running()` is unnecessary

2024-11-15 11:09 UTC, ZodiusInfuser commented on examples/tiny_fx/examples/showcase/rescue_vehicle.py
> +        if time.ticks_ms() - t > 500:  	# long press - toggle effect
The more robust way to do this check is `time.ticks_diff(time.ticks_ms(), t) > 500`. See: https://docs.micropython.org/en/latest/library/time.html#time.ticks_diff

Also, from my resting, I found having short press be effect switch, and long press be stop, felt like a better user experience

2024-11-15 11:09 UTC, ZodiusInfuser commented on examples/tiny_fx/examples/showcase/rescue_vehicle.py
> +            player.effects = [hazardEffect] if player.effects[0] is rgbEffect else [rgbEffect]
I'm surprised this worked! `player.effects` may appear as a list but is actually two functions hidden by properties. As such there may be cases where `effects[0]` would not equal the effect your originally entered into it.

Perhaps a safer way would be to have a separate `mode` variable that you use to set the new effect and then toggle for the next time e.g. `mode = not mode`

2025-01-06 10:01 UTC, ZodiusInfuser commented
@tyeth Have you had chance to look at my comments on this?

2025-01-14 11:29 UTC, closed without merging